#ifndef _EFI_SIMPLE_TEXT_INPUT_PROTOCOL_DEFINED_
#define _EFI_SIMPLE_TEXT_INPUT_PROTOCOL_DEFINED_

#define EFI_SIMPLE_TEXT_INPUT_PROTOCOL_GUID {0x38, 0x74, 0x77, 0xc1, 0x69, 0xc7, 0x11, 0xd2, 0x8e, 0x39, 0x00, 0xa0, 0xc9, 0x69, 0x72, 0x3b}

struct EFI_SIMPLE_TEXT_INPUT_PROTOCOL;

struct EFI_INPUT_KEY
{
    UINT16 ScanCode;
    CHAR16 UnicodeChar;
};

typedef EFI_STATUS(EFIAPI *EFI_INPUT_RESET)(IN EFI_SIMPLE_TEXT_INPUT_PROTOCOL *This, IN BOOLEAN ExtendedVerification);
typedef EFI_STATUS(EFIAPI *EFI_INPUT_READ_KEY)(IN EFI_SIMPLE_TEXT_INPUT_PROTOCOL *This, OUT EFI_INPUT_KEY *Key);

struct EFI_SIMPLE_TEXT_INPUT_PROTOCOL
{
    EFI_INPUT_RESET Reset;
    EFI_INPUT_READ_KEY ReadKeyStroke;
    EFI_EVENT WaitForKey;
};

#endif